// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WdAlarm.Infrastructure.Data;

#nullable disable

namespace WdAlarm.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210024350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WdAlarm.Core.Entities.ActionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AlarmCycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlarmDelayActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlarmPingActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ExecutedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PingId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlarmCycleId");

                    b.HasIndex("AlarmDelayActionId");

                    b.HasIndex("AlarmPingActionId");

                    b.HasIndex("PingId");

                    b.HasIndex("ScheduledTime");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ScheduledTime");

                    b.ToTable("ActionExecutions", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowPingNoTimerReset")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DelayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("TimeoutDuration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("VerificationMethod")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("Alarms", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AlarmPointTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByPingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.HasIndex("AlarmPointTime");

                    b.HasIndex("CompletedByPingId");

                    b.HasIndex("Status");

                    b.ToTable("AlarmCycles", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmDelayAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("AlarmDelayActions", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmPingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlarmId");

                    b.ToTable("AlarmPingActions", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.Ping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlarmCycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Payload")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ResetTimerRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("TimerWasReset")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VerificationError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VerificationProof")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("VerificationResult")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AlarmCycleId");

                    b.HasIndex("AlarmId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("Pings", (string)null);
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.ActionExecution", b =>
                {
                    b.HasOne("WdAlarm.Core.Entities.AlarmCycle", "AlarmCycle")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("AlarmCycleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WdAlarm.Core.Entities.AlarmDelayAction", "AlarmDelayAction")
                        .WithMany("Executions")
                        .HasForeignKey("AlarmDelayActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WdAlarm.Core.Entities.AlarmPingAction", "AlarmPingAction")
                        .WithMany("Executions")
                        .HasForeignKey("AlarmPingActionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WdAlarm.Core.Entities.Ping", "Ping")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("PingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AlarmCycle");

                    b.Navigation("AlarmDelayAction");

                    b.Navigation("AlarmPingAction");

                    b.Navigation("Ping");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmCycle", b =>
                {
                    b.HasOne("WdAlarm.Core.Entities.Alarm", "Alarm")
                        .WithMany("Cycles")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WdAlarm.Core.Entities.Ping", "CompletedByPing")
                        .WithMany()
                        .HasForeignKey("CompletedByPingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Alarm");

                    b.Navigation("CompletedByPing");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmDelayAction", b =>
                {
                    b.HasOne("WdAlarm.Core.Entities.Alarm", "Alarm")
                        .WithMany("DelayActions")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmPingAction", b =>
                {
                    b.HasOne("WdAlarm.Core.Entities.Alarm", "Alarm")
                        .WithMany("PingActions")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.Ping", b =>
                {
                    b.HasOne("WdAlarm.Core.Entities.AlarmCycle", "AlarmCycle")
                        .WithMany()
                        .HasForeignKey("AlarmCycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WdAlarm.Core.Entities.Alarm", "Alarm")
                        .WithMany("Pings")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");

                    b.Navigation("AlarmCycle");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.Alarm", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("DelayActions");

                    b.Navigation("PingActions");

                    b.Navigation("Pings");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmCycle", b =>
                {
                    b.Navigation("ActionExecutions");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmDelayAction", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.AlarmPingAction", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("WdAlarm.Core.Entities.Ping", b =>
                {
                    b.Navigation("ActionExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
